### ISSUE TITLE
How to select phpunit installation?

### ISSUE THREAD

**Issue by sandervanhooft** [adamwathan/sublime-phpunit#13]
Hi @adamwathan,

I'm using this package as suggested in [your Laravel TDD course](http://testdrivenlaravel.com).

Globally, I'm using `phpunit 6.0.6`. My Laravel app is using `"phpunit/phpunit": "~5.0",`.

When running a command from the `sublime-phpunit` package, it's running the globally installed `phpunit 6.0.6` - which isn't working ok for me.

Is there any way to use the version installed by composer instead?

Kind regards,

Sander

**Comment by adamwathan** [comment]
Hey @sandervanhooft! I think by default, it's going to use whatever version it finds when running `phpunit` from the same folder where it finds `phpunit.xml`.

What I would do it, is add `./vendor/bin` near the front of your `PATH` variable, so that the project-local `phpunit` binary is preferred over the global version.

Let me know if that works!

**Comment by sandervanhooft** [comment]
@adamwathan 

Wow, it works like a charm. You should definitely include this package in [your gist](https://gist.github.com/adamwathan/56029c37f9f6b8dc4fee1cc710b350ec) by the way.

Thanks! :)

**Comment by adamwathan** [comment]
Cool happy to help! 😊
