### ISSUE TITLE
Support for Hyper

### ISSUE THREAD

**Issue by pimpeters** [adamwathan/sublime-phpunit#18]
Is there going to be any support for Hyper?
Seems like iTerm and Terminal are the only useable terminals at this moment.

**Comment by c-fitzmaurice** [comment]
Second this, that would be sweeeeet.

**Comment by davidhemphill** [comment]
Would love to get a PR on this, but not sure what Electron provides as far as scriptability is concerned.

**Comment by zaknesler** [comment]
Any news on this?

**Comment by zaknesler** [comment]
**Update: So unfortunately, Electron does not support AppleScript, so I am afraid that the solution below is the only thing we have.**

So I've been playing around with this, and so far, I have this (excuse the tab indentation):

```applescript
on runTest(_command)
	tell application "Hyper" to activate

	tell application "System Events"
		repeat until exists window 1 of process "Hyper"
			delay 0.1
		end repeat

		keystroke "k" using {command down}
		keystroke "u" using {control down}

		keystroke _command
		keystroke return
	end tell
end runTest

on run argv
	set _command to item 1 of argv
	runTest(_command)
end run
```

This waits for Hyper to open before it attempts to run any commands, but the problem is that it requires you to allow Sublime to "control your computer," which is not ideal. I tried to make it work with the current solution for iTerm with no success

<img width="752" alt="screen shot 2018-07-06 at 3 35 04 pm" src="https://user-images.githubusercontent.com/7189795/42397010-3496290a-8132-11e8-8230-dc4f6b4d789d.png">

If anybody here has more experience with AppleScript, we can make this a PR in no time.
